// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrqtVHp7rIjKfFQWW9pH375r1X7qFFX6U',
    appId: '1:1059153884506:web:d7e6a0e52e7dd69d8b2f63',
    messagingSenderId: '1059153884506',
    projectId: 'foodapp-card',
    authDomain: 'foodapp-card.firebaseapp.com',
    databaseURL: 'https://foodapp-card-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-card.appspot.com',
    measurementId: 'G-4YD4BGDD64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIEBhf5cnAV_-9Zy4aMWx1o0R-OgI006o',
    appId: '1:1059153884506:android:71142a0a45ced5998b2f63',
    messagingSenderId: '1059153884506',
    projectId: 'foodapp-card',
    databaseURL: 'https://foodapp-card-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-card.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrqtVHp7rIjKfFQWW9pH375r1X7qFFX6U',
    appId: '1:1059153884506:web:d6a723fcdbcc95e98b2f63',
    messagingSenderId: '1059153884506',
    projectId: 'foodapp-card',
    authDomain: 'foodapp-card.firebaseapp.com',
    databaseURL: 'https://foodapp-card-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-card.appspot.com',
    measurementId: 'G-WL0QD121S5',
  );
}
